### ISSUE TITLE
Paginated table for trails

### ISSUE THREAD

**Issue by loreV** [loreV/SeC-Frontend#23]
The trail table shall be paginated. 
The pagination will work on a backend level. 
Each READ REST Response contains something like the following:
```
{
    status: "OK"
    errors: [ ],
    content: [ ],
    totalPages: 10,
    currentPage: 1,
    size: 15 <- specified by the frontend
    totalContent: 150
}
```
Frontend should look like: 
- The icon can be found at [](https://iconmonstr.com/bicycle-3-svg/)
![Screenshot 2021-02-28 at 12 33 35](https://user-images.githubusercontent.com/5400553/111659399-7d1df600-880d-11eb-9124-f43ee491f820.jpg)

**Comment by smarti04** [comment]
@loreV vogliamo farla con il numero della pagine o con una paginazione con lo scroll? tenendo sempre l'intestazione fissa in alto

**Comment by smarti04** [comment]
@loreV più che l'intestazione con scritto "CICLO" mettere un tooltip sull'icona e la farei più piccola rispetto ai bottoni CTA

**Comment by smarti04** [comment]
> @loreV vogliamo farla con il numero della pagine o con una paginazione con lo scroll? tenendo sempre l'intestazione fissa in alto

effettivamente però il doppio scroll nella pagina non è tanto bello

**Comment by loreV** [comment]
Paginata senza scroll (si doppio scroll darebbe problemi). Benissimo per la tooltip.

**Comment by smarti04** [comment]
@loreV la paginazione ora avviene solo FE? Nel senso, l'API restituisce tutti i percorsi?

**Comment by loreV** [comment]
La Paginazione deve avvenire lato backend. L'endpoint di preview è paginato. Questo weekend vi mostrerò tutta una serie di sviluppi ed Api da chiamare. Per ora si può usare un mock che simuli la tabella.

**Comment by loreV** [comment]
# What's been done
- Moved trailRaw to different page, avoiding double tables in same page
- Used Bootstrap powered pagination
